### ISSUE TITLE
Fix (remove) "javax.servlet.*" package version when processing the MANIFEST.MF

### ISSUE THREAD

**Issue by ifurnadjiev** [apache/tomcat-jakartaee-migration#39]
When "javax.servlet.*" package is specified in the MANIFEST.MF with version constraints like:

```
Import-Package: javax.servlet;version="[3.1.0,5.0.0)",
 javax.servlet.http;version="[3.1.0,5.0.0)",
```

it is converted to:

```
Import-Package: jakarta.servlet;version="[3.1.0,5.0.0)",
 jakarta.servlet.http;version="[3.1.0,5.0.0)",
```

and leads to unresolved dependencies in OSGi environment.
Removing or updating the version constraint to include 5 will fix the problem.

**Comment by laeubi** [comment]
> Removing or updating the version constraint to include 5 will fix the problem.

I think the real fix would be that the converter enters the appropriate version range it converts to, e.g. `[5, 6)` in this case or use the [Portable Java Contract Definitions](https://docs.osgi.org/reference/portable-java-contracts.html#portable-java-contract-definitions) instead.

**Comment by ifurnadjiev** [comment]
Any comment on the issue? Do you have plans to address it?

**Comment by markt-asf** [comment]
I'm a little uncomfortable with the idea of ignoring an explicit version range but if the user opts to use the migration tool that is an implicit choice to ignore the version range if it does not include Jakarta EE.

I'd prefer a solution that doesn't require parsing and understanding the existing version range but simply replaces it with something that will work on Jakarta EE.

I'm not aware of any plans to address this in the immediate future. Providing a PR is likely to improve the chances of this being fixed sooner rather than later.
